name: Build iOS App

on:
  workflow_dispatch:

jobs:
  build:
    name: Build App
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Install dependencies
        run: |
          brew install pnpm
          pnpm install
          cd ElementX
          pod install
          cd ..

      - name: Build for Simulator
        run: |
          xcodebuild -workspace ElementX/ElementX.xcworkspace \
                     -scheme ElementX \
                     -destination 'generic/platform=iOS Simulator' \
                     -derivedDataPath build \
                     build

      - name: Package App
        run: |
          cd build/Build/Products/Debug-iphonesimulator
          zip -r ElementX.app.zip ElementX.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ElementX-iOS-App
          path: build/Build/Products/Debug-iphonesimulator/ElementX.app.zip
          retention-days: 5
